name: "Custom javascript action for open an issue"
author: alialaa
description: "Opens a github issue"
inputs:
  token:
    description: "Github Token"
    required: true
  title:
    description: "Issue Title"
    required: true
  body:
    description: "Issue Body"
    required: true
  assignees:
    description: "Issue Assignees"
    required: true
outputs:
  issue: # id of output
    description: "The issue object as a json string"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "alert-octagon"
  color: "purple"
